### ISSUE TITLE
Frost Walker on Horse always active!

### ISSUE THREAD

**Issue by f0kx** [Majrusz/MinecraftMods#10]
When i enchant my horse armor with Protection and swiftness i also can frost walk over water ... but i dont have the frost walker enchanment!

FORGE: 1.16.4 - 35.1.36
WONDERFULENCHANMENT: wonderful-enchantments-1.16.4-0.10.3

**Comment by Majrusz** [comment]
Thanks for your feedback! This will be fixed in the latest update. (0.10.4)
