### ISSUE TITLE
Updating to Latest Update Crashes on Startup

### ISSUE THREAD

**Issue by KakashoLin** [Majrusz/MinecraftMods#105]
Updating Majrusz's Enchantments to the recent 1.10.8 update will cause the game to crash upon boot up. The tricky thing it doesn't seem to create a crash log so got this information mainly from the lastest.log and manually pulled back recent updates till the issue was pin pointed.

Reverting back to 1.10.7 fixes the issue and the game loads. 

Here is the log file: https://pastecode.io/s/v9jr0gh2

**Comment by Majrusz** [comment]
Hello, thanks for the report, I have uploaded a new rebuilt version as the previous one did not have all necessary files
