### ISSUE TITLE
Smelter 1.12.2-0.6.0

### ISSUE THREAD

**Issue by TestZIL** [Majrusz/MinecraftMods#12]
The Smelter in this update (1.12.2) it doesn't work, Are there any new updates for Minecraft version 1.12.2 that will fix it?

(( I didn't check the other enchantments ))

**Comment by Majrusz** [comment]
It is possible that the enchantment works, because in previous versions (for example 0.6.0) this enchantment gave a chance to smelt a block depending on the level. Have you tried with the Smelter III? There should be a 100% chance to smelt.

**Comment by TestZIL** [comment]
> It is possible that the enchantment works, because in previous versions (for example 0.6.0) this enchantment gave a chance to smelt a block depending on the level. Have you tried with the Smelter III? There should be a 100% chance to smelt.

yes i have tried the Smelter III on 64 blocks of iron ore , and it doesn't work }: <( I did the same thing in version 1.16.4 and it works fine ) 
^
 and it is the only mod i have ( i didn't download other mods with it )
