### ISSUE TITLE
Semi-Incompability with Spartan Weaponry

### ISSUE THREAD

**Issue by crafting-Aaron** [Majrusz/MinecraftMods#13]
Having a weapon that has the two-handed attribute will constantly give mining fatigue. If a shield has the Absorber enchant, it will constantly try to remove the effect breaking the shield. Is there a way to prevent this by checking if the user is holding a two-handed weapon?

**Comment by Majrusz** [comment]
Hi I have added minimum required time for Absorber to work (default 2 seconds, it is configurable) and this will fix problem with other modifications. This will be available in the next update.
