### ISSUE TITLE
Suggestion: Hunter enchantment on crossbows

### ISSUE THREAD

**Issue by crafting-Aaron** [Majrusz/MinecraftMods#16]
Having Hunter on vanilla crossbows would turn them into a sort of sniper weapon. Always loved the idea of being a sniper with archery in Minecraft and this enchantment is perfect. It would not be overpowered as it depends on the distance rather than being flat damage like Power. This is even more balanced now that Hunter has been updated to do less damage when close to a target so spamming a hotbar of crossbows up close would actually punish you rather than get better results.

If possible, could you implement this into the Spartan Weaponry Heavy Crossbow? It is understandable if you won't as its kind of hard implementing enchantments on modded weapons. Especially a crossbow that has its own loading & aiming mechanics with bolts instead of arrows.

Love the growth of this mod! Will try out with Progressive Difficulty for the bleeding arrows.

**Comment by Majrusz** [comment]
Hello, thanks for your feedback! I will see how difficult to implement it is and try to add it at least on minecraft crossbows.

**Comment by Majrusz** [comment]
I've added the Hunter to work on basic crossbows, in the future updates I'll try to add it on crossbows from modifications as well. This functionality will be available in the next update.

**Comment by crafting-Aaron** [comment]
Awesome. Thank you for your work!

PS: I could contribute on the Spanish translation if you would like. Just tell me how it works and I'll help you.

**Comment by Majrusz** [comment]
That would be nice! You should download en_us.json file from this location https://github.com/Majrusz/WonderfulEnchantmentsMod/tree/1.16.4/src/main/resources/assets/wonderful_enchantments/lang, rename it to es_es.json and replace all text inside file with new language. Then either send it to me in private message or create a pull request to add a new file.

**Comment by crafting-Aaron** [comment]
Great! I'll work on it

**Comment by crafting-Aaron** [comment]
Hello!
Sorry I have not been available, I tried to make a pull request but the button was not available for me.
Edit: I just found a way to upload the file. I added a description on the commit for some details. Let me know what you feel about the translation!

**Comment by Majrusz** [comment]
Thanks! Everything seems to work fine I will add your translation in the next mod update.
