### ISSUE TITLE
weird enchanting table glitch with whisperwoods 1.16.4

### ISSUE THREAD

**Issue by HeroMeDavid** [Majrusz/MinecraftMods#17]
When I open the enchanting table I see this. https://i.imgur.com/gZMNPpS.png

I have confirmed that it's either wonderful Enchantments or Whisperwoods and not majrusz-library.

My full mod list:
Forge 35.1.37
jei-1.16.4-7.6.1.65
majrusz-library-1.16.4-1.2.0
whisperwoods-1.16.4-2.0.0
wonderful-enchantments-1.16.4-1.0.1

**Comment by Majrusz** [comment]
Thanks for reporting this, unfortunately I can not find the cause of this bug. Anyway, I will still try to fix it.

**Comment by Majrusz** [comment]
Okay, I managed to partially fix it, unfortunately with this mod Enlightenment enchantment will not work properly. It will only gives experience bonus, but not enchantment table level bonus.

**Comment by mariomurfer** [comment]
I have the same problem on 1.16.5 and I'm using the 1.1.1 version of Wonderful enchantments. I have a modpack with 49 mods and today I installed wonderful enchantments and the enchanting table gave the same error. Is there a way to fix this?

**Comment by Majrusz** [comment]
Today I will release the 1.1.2 version where this bug should not exist anymore.
