### ISSUE TITLE
Server Crash with latest version when attempting to run the mod on a dedicated server [1.16.5]

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Majrusz/MinecraftMods#22]
Forge Version: 36.0.43
Wonderful Enchantments Version: 1.1.0
Majrusz Library version: 1.4.0
Minecraft Version: 1.16.5

Crash Report: 
[crash-2021-02-26_18.19.42-server.txt](https://github.com/Majrusz/WonderfulEnchantmentsMod/files/6051836/crash-2021-02-26_18.19.42-server.txt)
Latest Log:
[latest.log](https://github.com/Majrusz/WonderfulEnchantmentsMod/files/6051842/latest.log)

I've noticed that after updating my modded server to the latest version of wonderful enchantments and Majrusz's library, this crash now occurs whenever I attempt to start up my server. This issue stops happening if I roll the server back to the previous version of the mod (1.0.4).

**Comment by Majrusz** [comment]
Thanks for reporting this! I have fixed this bug and a working version will be available soon.
