### ISSUE TITLE
smelting + fortune not doubling with modded ores

### ISSUE THREAD

**Issue by HeroMeDavid** [Majrusz/MinecraftMods#23]
smelting and fortune does drop more ingots for vanilla ores like iron and gold but it doesn't work on ores like copper from mekanism.

**Comment by Majrusz** [comment]
Hi, this enchantment only works with these two ores for now. I will consider adding list when you can specify what ores should be affected by this enchantment.

**Comment by Majrusz** [comment]
It took me a while, but finally in the next update in the configuration file, you will be able to add ores that should drop more ingots.
