### ISSUE TITLE
(1.16.4) Telekinesis make duplicate items with other mod

### ISSUE THREAD

**Issue by mikado0605** [Majrusz/MinecraftMods#24]
Version : 1.16.4
Mod : Wonderful Enchantments + Enigmatic Legacy

There is an Acc Items from enigmatic legacy mod that give player who wear it +1 Fortune Level (ex Ring of the Seven Cursed), somehow instead work like vanilla minecraft , it duplicate any blok that pickaxe with telekinesis enchantment can break Such Iron Block, Diamond Block, Enchanting Table, etc

well i can just disable it but telekinesis make my life so much easier, but it would be nice if you could fix it
Thanks

**Comment by Majrusz** [comment]
Thanks for reporting this. In the next update Telekinesis will not be duplicating items with some other modifications.
