### ISSUE TITLE
2 new enchantment suggestions related to potion effects

### ISSUE THREAD

**Issue by crafting-Aaron** [Majrusz/MinecraftMods#26]
Hello! The mod is coming well along. It might even be the go to choice for rpg modpacks. Here are some suggestions I came up with inspired by the Absorber enchantment and Facade move and Guts ability from Pokemon.

Introduction:
With how a lot of mods add new potion effects, or mobs that poison, paralyze, decay, etc. It would be great to have two enchantments that could help you counter with both defense and offense when being overwhelmed with various potion effects.
If possible, this enchantments will not be able to stack with another copy, similar to how a full Thorns set doesn't make a difference.

~Payback or Karma I-III~ (Sword/Helmet)
This enchantment adds (level) points of dmg when under the effect of a negative effect or being on fire.
At level 3, if you at least have 3 or more effects, all melee attacks are critical.

This means means if you encounter a dungeon and end up being poisoned, paralyzed, bleeding, etc. you might be able to survive by hitting harder. A config option to add or remove potions effects would be great and if to disable the dmg stacking per effect.

~Immune System or Mithridatism* I-III~ (Shield/Chestplate)
*(this word originated by the tale of Mithridates VI a royal heir who feared to be assassinated by poison by his mother. He then fled to the wild and took small doses of poison to supposedly develop an immunity or resistance to poison)
Version 1
This enchantment increases armor by (level) points per active negative effect. At level 3, gives a heart of absorption for 3 seconds every time a negative effect is introduced.
Version 2
This enchantment gives (level) hearts of absorption every time a negative effect is introduced. At level 3, you gain 3 armor points for 9 seconds every time a negative effect is introduced.

Version 2 could have the absorption run for 30 seconds or increase by level.

This enchantment would prevent being obliterated by the stacking of negative effects when dealing with a dungeon like having poison, wither, and being on fire at the same time. Especially if you have the Better Hurt Timer mod installed which reduces or removes the invincible frames when taking or dealing damage.

Conclusion:
After playing modpacks like RLCraft, I realized there is barely any way to counter negative effects from mods without having a milk bucket or splash milk potion which don't even stack in the inventory. Rather than just having milk with you all the time, it would be more fun to actually use the negative effects to your advantage with these enchantments.

**Comment by Majrusz** [comment]
Wow, great ideas! I will add both of them in the next update :)

**Comment by Majrusz** [comment]
One of your ideas is currently finished and will be available in the next update. Here is detailed information about it: https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments/pages/enchantment-descriptions/mithridatism

**Comment by crafting-Aaron** [comment]
It works great! I did not know it was possible to partially reduce damage from an effect so that is why i suggested armor but this is better.
