### ISSUE TITLE
Smelter lag with netherrack [1.16.5]

### ISSUE THREAD

**Issue by borgaboo** [Majrusz/MinecraftMods#28]
Smelter works on netherrack which is amazing, thank you, nether bricks are my goddamn favorite. However, I've noticed that the bricks get picked up but don't appear in my inventory until I open up a secondary GUI or leave the nether. For example, they did not appear until I opened and closed my backpack then re-entered my normal inventory. Without my backpack, they didn't appear until I left the nether.

**Comment by Majrusz** [comment]
Hi, thanks for reporting this, in version 1.16.4 everything works fine and I think it might be caused by Forge for 1.16.5. As soon as I upgrade the project to 1.16.5 then I will try to fix it.
