### ISSUE TITLE
Telekinesis from Wonderful Enchantments +  Luck Scarf dup itens

### ISSUE THREAD

**Issue by hadDOTpy** [Majrusz/MinecraftMods#30]
Any broken block with an enchanted tool with Telekinesis (from Wonderful Enchantments) adds 2 of the block/item in the inventory

How to reproduce the issue:

• Enchant an pickaxe with Telekinesis
• Equip Luck Scarf on curios slot
• break a block

Wonderful Enchantments: wonderful-enchantments-1.16.4-1.1.2
Artifacts: Artifacts-1.16.5-2.8.4
Forge: 36.1.2

**Comment by Majrusz** [comment]
It was fixed in version 1.1.3.
