### ISSUE TITLE
[1.16.5] Smelter is smelting both cobblestone and stone to smooth_stone.

### ISSUE THREAD

**Issue by Zothen1973** [Majrusz/MinecraftMods#31]
Mod Version 1.2.0

I am quite sure that wasn't always an issue, but now cobblestone and stone isn't smelted to stone anymore, but to smooth_stone.

![grafik](https://user-images.githubusercontent.com/77007295/117881657-cb012880-b2a9-11eb-969e-8e6e8acaa90f.png)

**Comment by Majrusz** [comment]
Hi, my mod is probably colliding with other mod. Can you give me a link/list of your currently installed mods?

**Comment by Zothen1973** [comment]
Sure, but I am afraid it's rather long...

[mod-list_2021-05-13_12.00.19.txt](https://github.com/Majrusz/WonderfulEnchantmentsMod/files/6477774/mod-list_2021-05-13_12.00.19.txt)

**Comment by Zothen1973** [comment]
After further testing, it only seems to happen on our dedicated server.

Used the same mods and configs on both single- and multiplayer.

**Comment by Zothen1973** [comment]
Any idea what's causing this? Maybe a sync problem?

**Comment by Majrusz** [comment]
Unfortunately, I still have not found what is causing this bug

**Comment by Zothen1973** [comment]
Are you iterating only 1 smelting recipe or can it be that other smelting recipes from mods are added on top of that?

**Comment by Zothen1973** [comment]
Okay, after further testing, I found the cause: when wearing the "Lucky Scarf" from the mod "Artifacts" in the Neck curios slot, mined stone is converted to smooth stone. As soon as the scarf is taken off, mined stone is smelted to stone as expected.

The "Lucky Scarf" is supposed to add 1 level of fortune to the player, so can you fix this in your side?

**Comment by Majrusz** [comment]
It is most likely the fault of this mod, as it apparently causes loot to generate twice.

**Comment by Zothen1973** [comment]
I think if that was the case, the mod "Vanilla Tweaks" "blazing" enchantment would have the same issue, but that one is working flawlessly. It also takes fortune into account regarding output.

**Comment by Majrusz** [comment]
I can not reproduce this bug with Wonderful Enchantments 1.3.1 and Artifacts 2.8.4. Smelter enchantment works properly, you should download the latest version of my mod and try again. Otherwise other mod may cause this bug.

**Comment by Zothen1973** [comment]
Hmm, did you put on the Lucky Scarf while testing?
