### ISSUE TITLE
Item duping because telekinesis enchantment

### ISSUE THREAD

**Issue by bstlyc** [Majrusz/MinecraftMods#36]
item dupe when i try mine or breaking block with tools that enchanted by telekinesis

**Comment by Majrusz** [comment]
Can you provide what mods are you using and what are your Wonderful Enchantments and Forge versions?

**Comment by RealDovahbear** [comment]
This is caused by the mod Project MMO. I don't know if there's a workaround, maybe try reporting this bug there too since it's caused by both of the mods being together?

Edit: this enchantment worked as intended when PMMO was NOT installed, but after adding it, the dupe bug occurs

**Comment by rperraudeau** [comment]
Hello,
I can confirm this.
I tried to change some PMMO config but it doesn't fix the issue
