### ISSUE TITLE
[MC 1.12.2]Wonderful Enchatments and Quark

### ISSUE THREAD

**Issue by Bruno-Calasans** [Majrusz/MinecraftMods#38]
My game crashed right now but, when i tried to play, it was normal. But i got a warning from VanillaFix mod: https://drive.google.com/file/d/1U1AHy-VfIueK9WcEERl6ExCL3PpSz_DF/view?usp=sharing

Crash logs:

https://drive.google.com/file/d/1hMwq3pCvQUvNf6vxFNu9ARiDU3dbedL4/view?usp=sharing

https://drive.google.com/file/d/19ck1FzVxF3-_0FdlfnfUcrJz0uDYIY4h/view?usp=sharing

**Comment by Majrusz** [comment]
Sorry, unfortunately, I am no longer developing this mod for Minecraft 1.12.2 :( There is too much difference between versions
