### ISSUE TITLE
Phoenix Dive Enchantment hurting friendly creatures/mounts

### ISSUE THREAD

**Issue by Himynameissomeone** [Majrusz/MinecraftMods#39]
First off- Thank you for the mod! It's great and I love nearly all the features of it!
Except... Phoenix Dive
The problem here is that the enchantment causes unilateral damage to all creatures within a 5*5 area. This is problematic for several reasons:
1. It cannot distinguish between "friendly/neutral" and "hostile" mobs. This means simply falling from a distance of 3 or above causes me to accidentally hurt my wolves, villagers, cats etc. The damage is actually quite powerful, with one jump taking out half hp of dogs.
2. Causes damage to any modded mounts that are taller than 3 blocks. Dismounting such mounts causes the Phoenix Dive to activate, setting my modded mounts on fire. This is especially the case for Ice and Fire dragons, where simply dismounting causes phoenix dive to activate and set the dragons on fire. 
3. The Config files do not solve this issue. The Config files let me choose the area of the damage with the minimum set to 1*1 blocks. This still causes harm to tall mounts and any unfortunate creatures that I fall unto. 

To deal with this issue, I think there may be some possible solutions:
1. Add a config that lets you turn off damage, or set the area of damage to 0 blocks.
2. Implement a way to "distinguish" between hostile and friendly/tamed mobs.

I'm no expert in modding and I believe that there may be much more better ways to solve this. It's just been very frustrating to set my own mounts/villagers on fire every time I accidentally fall down from something. Thanks so much for the help!

**Comment by Himynameissomeone** [comment]
One more issue- some enchantments cannot be applied on modded items. For example, this mod's shield enchantments cannot be applied to the shields provided by the Atum mod. Are there ways to fix this issue?

**Comment by Majrusz** [comment]
Thanks for reporting this. It is fixed and it will be working as you described in the next update :)

**Comment by Majrusz** [comment]
I mean it will be ignoring friendly creatures
