### ISSUE TITLE
[Feature Request | Issue] Blacklist For Entities (Sixth Sense)

### ISSUE THREAD

**Issue by Seikikai** [Majrusz/MinecraftMods#45]
Since There Are Mods That Uses Entities As Blocks, In This Case [Improved Windows](https://www.curseforge.com/minecraft/mc-mods/improved-windows) Wich Uses Entities To Emulate Windows Panels, It Will Be Good To Add A Blacklist For Entities That You Want To Filter Like In This Case The Windows Frames Or In Other Cases Entities Like Armor Stands, Golems, Fishes Or Other Depending Of What The Player Wants.

![imagen](https://user-images.githubusercontent.com/54079357/139757412-180d116c-d264-4a3b-ba84-b27b0ba19356.png)

Also, For Some Reason When The Sixth Sense Activates, The Overlay Doesn't Dissapear In This Entity, Even If I Unequip The Enchanted Helm.

![PicA](https://user-images.githubusercontent.com/54079357/139763863-c55cddea-edac-4a56-961b-767b73f53e05.jpg)
![PicB](https://user-images.githubusercontent.com/54079357/139763884-9de53282-26e0-4a65-8935-a809e2abff3c.jpg)

**Comment by Baggytrousers27** [comment]
Got a named iron golem guarding my front door but landing next to him with Phoenix dive sets him on fire and he punches me into next week. Perhaps another blacklist for entities affected by it?

**Comment by 2127d** [comment]
Hey can i get a download of this code to experiment with

**Comment by Majrusz** [comment]
At the moment Sixth Sense has been removed, but once I rework and add it back I will add this config

**Comment by Majrusz** [comment]
Okay, so Sixth Sense was readded, but it now works different than it used to. That issue should not occur as entities now must emit some sound to be highlighted
