### ISSUE TITLE
"Fishing Fanatic" and offhand fishing rods

### ISSUE THREAD

**Issue by TaeoG** [Majrusz/MinecraftMods#46]
A mod called "Fishing Real" makes the game pull up fish entities instead of fish items. Because of this, I typically fish with my offhand and hold a weapon in the main hand to kill the entities as they come out of the water. I now have a sword with "Fishing Fanatic II" on it, haha. Also, its unclear if the fishing fanatic enchant works if you put it on your offhand fishing rod either

**Comment by Majrusz** [comment]
Haha :D In the next update (for 1.18.1) it will be fixed because right now fishing fanatic does not work properly when you have it on your offhand
