### ISSUE TITLE
Leech Enchantment Causing Server Crash

### ISSUE THREAD

**Issue by popcorn1111** [Majrusz/MinecraftMods#47]
Unless I am misreading something, the Leech enchantment is causing our server to crash. It has occurred a few times now, and the server crashes always correspond to when someone with a Leech-enchanted sword was fighting. If needed, I can attach the other crash reports.

[crash-2021-11-29_05.31.53-server.txt](https://github.com/Majrusz/WonderfulEnchantmentsMod/files/7622204/crash-2021-11-29_05.31.53-server.txt)

**Comment by RXJpaw** [comment]
I suspect this occurs when a non-player entity attacks something with status effects and the mod cant handle giving an non-player entity status effects from Leech,

**Comment by Majrusz** [comment]
Thanks for reporting this. In the next update (for 1.18.1) it will be fixed! :)
