### ISSUE TITLE
Particles...

### ISSUE THREAD

**Issue by AefRal** [Majrusz/MinecraftMods#49]
Regarding the Dodge enchantment.
I'm blinded by particles every time it procs.

I've checked the configs for some kind of particle setting, didn't find any.
Wiki doesn't say either.
I like the effect but hate not being able to see my enemy in tight quarters.
Is there a command or some way to turn it off?

Thanks.

**Comment by Majrusz** [comment]
Done, in the next update there will be a new parameter in a config to disable that :)

**Comment by AefRal** [comment]
Thank you.
