### ISSUE TITLE
Can’t launch the game with Majrusz’s Enchantments

### ISSUE THREAD

**Issue by Nevrai** [Majrusz/MinecraftMods#52]
This error appears when launching the game:

![majrusz error](https://user-images.githubusercontent.com/59761487/182189233-83657df2-3ede-46fb-b7fc-48708c52f6fb.png)

However, Majrusz Library _is_ installed, and it’s the latest version of it for 1.18.2.

### Versions
* **Minecraft:** 1.18.2
* **Majrusz’s Enchantments:** 1.6.2 (latest)
* **Majrusz Library:** 2.7.2 (latest)
* **Forge:** 40.1.68 (latest)

**Comment by Majrusz** [comment]
Can you send me a list of all your mods?

**Comment by Nevrai** [comment]
Originally, I had a lot of mods, but I decided to create a clean test instance with just Majrusz’s Enchantments and Majrusz Library, and it still crashes.

* **latest.log** = https://pastebin.com/raw/ncJFC9tk
* **Crash report** = https://pastebin.com/raw/9Uvg28nS

**Mod list:**
* majrusz-library-1.18.2-2.7.2.jar
* wonderful-enchantments-1.18.1-1.6.2.jar

**Versions:**
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68

**Comment by Parkprkr** [comment]
I've been having the same problem

**Comment by Majrusz** [comment]
Thanks for the report, it should be fixed in 1.6.3 release

**Comment by Nevrai** [comment]
Great to hear, Majrusz. Thank you!
