### ISSUE TITLE
[1.19.1] Loading alongside Flint Instead of Wood stops activated chests from generating loot.

### ISSUE THREAD

**Issue by Baggytrousers27** [Majrusz/MinecraftMods#53]
Forge 1.19.1 42.0.1
fiow-19.0.1
majrusz-library-1.19.1-2.14.0
majruszs-enchantments-1.19.1-1.7.3

Right clicking on an unloaded chest (Starter chest for instance) marks the inventory as loaded without opening it. Opening it afterwards reveals an empty chest. Breaking the chest however spits out loot as normal.
Loot generates normally with FIoW and Majrusz by themselves.

[debug.log](https://github.com/Majrusz/MajruszsEnchantmentsMod/files/9243109/debug.log)

P.S Not sure if this is a 1.19-1.19.1 thing but have submitted the issue to Skyjay1 as well.

**Comment by Majrusz** [comment]
Thanks for the report, fixed here 1d85cbeb4c80f1766e71e39e7480f301ff51bb43 and soon a new update will be available
