### ISSUE TITLE
[Suggestion 1.18.2] Fuse Cutter

### ISSUE THREAD

**Issue by INooBTooMuch** [Majrusz/MinecraftMods#56]
Fuse Cutter isn't compatible with modded shields from [Cyclic](https://www.curseforge.com/minecraft/mc-mods/cyclic), [Alex's Mobs](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs), [Forbidden and Arcanus](https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus), [Artifacts](https://www.curseforge.com/minecraft/mc-mods/artifacts) and maybe others.

Versions :
Minecraft : 1.18.2
Forge : 40.1.80
Majrusz'sEnchantments : 1.6.3

**Comment by Majrusz** [comment]
Hi, thanks for the report, it took me a while to start working on it, but shield enchantments should be compatible with the next update for 1.19.3
