### ISSUE TITLE
[1.19.2] Fire issue with the dodge enchantment

### ISSUE THREAD

**Issue by someonedeepintheinternet** [Majrusz/MinecraftMods#57]
So i use the dodge enchantment and it dodges literally anything, which includes fire. My issue is, i use a mod with a item that gives fire resistance and it still dodges the fire......and the durability just goes crazy down even though i'm immune to fire.

**Comment by Majrusz** [comment]
Hi, it should be fixed in 1.7.5 version, what version are you using?

**Comment by someonedeepintheinternet** [comment]
majruszs-enchantments-1.19.2-1.7.5.jar

**Comment by Majrusz** [comment]
Thanks for the report, fixed here a82779b32648d45f710e7b10c53240500800edd2 in the next update it should be an issue anymore
