### ISSUE TITLE
[Feature request] option to remove telekinesis' particles

### ISSUE THREAD

**Issue by LeoBeliik** [Majrusz/MinecraftMods#58]
insta mining with telekinesis makes a lot of particles constantly floating in your face, would be nice to have an option to disable them :)
![]()

<img src="https://user-images.githubusercontent.com/11804768/202557881-58b4d4b4-4b7a-4f3b-aeb5-8efd95b0afc2.png" data-canonical-src="https://user-images.githubusercontent.com/11804768/202557881-58b4d4b4-4b7a-4f3b-aeb5-8efd95b0afc2.png" width="450" height="300" />

**Comment by Majrusz** [comment]
Hi, thanks for the report. I have made these particles much smaller and disappear faster, but if they still make your mining process annoying then you will be able to disable them completely with the next update 👍

**Comment by Majrusz** [comment]
![2022-12-31_14 34 10](https://user-images.githubusercontent.com/57394914/210138525-9f22003e-e38c-49d8-9e60-d61ff7641c4f.png)
And here is the screenshot
