### ISSUE TITLE
1.19.2 Telekinesis Dupe

### ISSUE THREAD

**Issue by xd4rkzghost01** [Majrusz/MinecraftMods#63]
Hi There !
I play on a Singleplayer map. Alone. With 212 mod :D i manually download from curseforge. I was thinking the issue was cause by [Job+](https://beta.curseforge.com/minecraft/mc-mods/jobsplus) Mod (due to Lumberjack skill double log drop) but it seems that the enchant telekinesis dupe every block/workstation in the game. As i can see it is also an older issue #36. I sadly post this "same" issue" on the page of [Job+](https://github.com/DAQEM/JobsPlus/issues/74) and i manage to find that after loosing my axe ahah.

Minecraft 1.19.2
Forge 43.2.0
Optifine (latest for 1.19+)
and 211 other mods :D

If you need more, just tell me.

Log from 23/02/17 When i think i unlock Lumberjack Double Log skill (in a .rar folder)
[2023-02-17-1.log.gz](https://github.com/DAQEM/JobsPlus/files/10775475/2023-02-17-1.log.gz)

Latest Log From 23/02/18
[2023-02-18-1.log.gz](https://github.com/DAQEM/JobsPlus/files/10775518/2023-02-18-1.log.gz)

And a New Log, exit game then reload and mine/chop blocks to see if it will be in the log.
[latest.log](https://github.com/DAQEM/JobsPlus/files/10775519/latest.log)

Video/Screenshot?
Dunno how to load video so i transform them into .gif
Pickaxe
![Pickaxe](https://user-images.githubusercontent.com/63568312/219907960-f49c95a9-9d6a-45fa-b845-62013f9605ff.gif)

Axe
![Axe](https://user-images.githubusercontent.com/63568312/219908001-2960a45c-fac2-4d14-96a7-b3ba4f3767fd.gif)

Shovel
![Shovel](https://user-images.githubusercontent.com/63568312/219908055-5988a4e5-8892-4a39-a7d5-07953a45e3c6.gif)

And there my Tools
![2023-02-18_20 43 36](https://user-images.githubusercontent.com/63568312/219908150-bf21d51b-95a9-40d5-9dc2-5b45c33b3d34.png)
![2023-02-18_20 43 42](https://user-images.githubusercontent.com/63568312/219908151-20273cae-8577-4bbf-9e40-6c1b96293080.png)
![2023-02-18_20 43 45](https://user-images.githubusercontent.com/63568312/219908152-dd92777e-1e49-4863-812c-7e7f7ee4d701.png)

**Comment by Majrusz** [comment]
Hello, sorry for the late response, but it got eventually fixed with the latest 1.10.0 release!
