### ISSUE TITLE
[1.19.2] Breaking Supplementaires' jar with a tool that has Telekinesis enchant drops the loot table multiple times

### ISSUE THREAD

**Issue by LeoBeliik** [Majrusz/MinecraftMods#66]
majrusz-library-1.19.2-3.3.0
majruszs-enchantments-1.19.2-1.8.1
moonlight-1.19.2-2.2.31-forge
supplementaries-1.19.2-2.3.4

Video:
https://imgur.com/a/dUzAk1l

**Comment by Majrusz** [comment]
Hi, it seems that there is some other mod that cause that bug, I cannot reproduce that bug with these versions:
- majrusz-library-1.19.2-4.0.0
- majruszs-enchantments-1.19.2-1.8.2
- moonlight-1.19.2-2.2.34
- supplementaries-1.19.2-2.3.15

**Comment by LeoBeliik** [comment]
Tested it with those versions and no other mods and it definitively stills happens. Note that hand placed urns don't have loot inside.
Also using Forge 43.2.13

**Comment by Majrusz** [comment]
Okay, you are right, I have tested it on naturally generated urns and it works as you said. However I am afraid that I wont be able to fix it on my side and I have opened an issue on Supplementeries mod https://github.com/MehVahdJukaar/Supplementaries/issues/629 (lets keep this issue opened until the author responds or fix this issue)

**Comment by Majrusz** [comment]
Okay, so the author of Supplementaries fixed that and with the latest release it should not be an issue anymore, anyway thanks for the report
