### ISSUE TITLE
Crash on loading client

### ISSUE THREAD

**Issue by jouki** [Majrusz/MinecraftMods#71]
Hey,

as per title the game crashed when I tried load the game. Can you look at it?
Here's the log:
https://gist.github.com/jouki/791b84b9f07a162828887b1c995a0b14

Cheers,
Jouki

**Comment by Majrusz** [comment]
Thanks for the report, I fixed that d5e994e9fff35ab5ee7c3bd6cc8cd0a090ab4306 and soon new mod version will be available with that fix included

**Comment by Majrusz** [comment]
Hi again, 1.9.1 has been released and it should not be an issue anymore
