### ISSUE TITLE
Make Misanthropy workable with all illagers [including mobs tagged as illagers in mod]

### ISSUE THREAD

**Issue by betterworld-sjq** [Majrusz/MinecraftMods#75]
Since it's incompetible with Sharpness, I can't find a reason to enchant it on. Smite can deal bonus damage to all undead mobs, so   this enchantment should work with all illagers so it deserves its status incompetible with sharpness and smite.

**Comment by Majrusz** [comment]
Hello, thanks for the report, there was a bug in library that I fixed and soon I will release a new library version with that fix included
