### ISSUE TITLE
[1.20.1] Dodge enchantment dodges all damage types

### ISSUE THREAD

**Issue by mxruben** [Majrusz/MinecraftMods#76]
I don't know if this is intentional, but the dodge enchantment can dodge any type of damage, including things such as drowning and fall damage. This seems a little overpowered and also just doesn't make sense (How would you dodge running out of air?). I think it would be more balanced and intuitive if the enchantment only dodged damage from other entities.

**Comment by Majrusz** [comment]
Hello, thanks for the report, I have fixed that here 4397e019176420b6811d0c9db6ff737a6f2f1f9b and soon I will release a new mod version
