### ISSUE TITLE
The new versions (1.9.1 + 5.0.0 lib) serverconfig file doesn't work. (forge 1.19.2)

### ISSUE THREAD

**Issue by zzzaitegui** [Majrusz/MinecraftMods#77]
The enchantments were perfectly configurable with the previous version, but now they revert to semi-default values on server restart.

**Comment by Majrusz** [comment]
Hello, thanks for the report, I have fixed that here f068bce656e1211b5e5c8197328b9da0c642d7d4 and soon I will release a new mod version
