### ISSUE TITLE
requires mlib 5.1.0 or above but below 6.0.0

### ISSUE THREAD

**Issue by x-j0nnay-x** [Majrusz/MinecraftMods#80]
i have mlib 6.01 installed but this error comes up, can you push an update to fix this? seems like having mods out of date is a bad thing

**Comment by Coraline774477** [comment]
I have the same thing happen to me, I'll have to uninstall Majrusz's Enchantments for now and replace it with an alternative enchantment mod for 1.20.1 till you (@Majrusz) bump it's version up to require Majrusz Library 6.0.0 or above (6.0.1 to be exact) in order for it to work with mlib 6.0.1

**Comment by Majrusz** [comment]
Hello, I am working on it, but at the moment please downgrade library to 5.1.2

**Comment by Majrusz** [comment]
Fixed, check out the latest 1.10.0 release!
