### ISSUE TITLE
I got the latest version of majrusz's library and majrusz's enchantments for forge and i crashed

### ISSUE THREAD

**Issue by jojofenin99** [Majrusz/MinecraftMods#82]
[latest.log](https://github.com/Majrusz/MajruszLibrary/files/13273645/latest.log)
[crash-2023-11-06_18.42.02-client.txt](https://github.com/Majrusz/MajruszLibrary/files/13273646/crash-2023-11-06_18.42.02-client.txt)
here is the crash and normal log

**Comment by Majrusz** [comment]
Fixed in library mod https://github.com/Majrusz/MajruszLibrary/issues/41
