### ISSUE TITLE
[1.20.1] Game crashes in the loading screen on mod version 1.10.2 and 1.10.1.

### ISSUE THREAD

**Issue by fare-SansUndertale** [Majrusz/MinecraftMods#90]
`Description: Initializing game`

`java.lang.NullPointerException: Registry Object not present: majruszsenchantments:dodge`

Forge 47.2.5

I downgraded each one of the library mods and it still crashed with the same error message.
[latest.log](https://github.com/Majrusz/MajruszsEnchantmentsMod/files/13388398/latest.log)
[crash-2023-11-16_20.21.23-client.txt](https://github.com/Majrusz/MajruszsEnchantmentsMod/files/13388418/crash-2023-11-16_20.21.23-client.txt) (first crash)
[crash-2023-11-16_21.01.07-client.txt](https://github.com/Majrusz/MajruszsEnchantmentsMod/files/13388426/crash-2023-11-16_21.01.07-client.txt) (latest crash)

**Comment by fare-SansUndertale** [comment]
okay on the loading screen and ingame, the seems to have stopped with the latest version of Majruszslib (6.1.6)
ty!! ^-^

**Comment by Majrusz** [comment]
Hello, thanks for the report, the proper fix is available with the latest release (6.1.7)
